# Generated by Django 6.0.2 on 2026-02-08 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('S1', 'Semestre 1'), ('S2', 'Semestre 2')], max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(blank=True, max_length=50, null=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenoms', models.CharField(max_length=150)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('mention', models.CharField(choices=[('INFORMATIQUE', 'Informatique & Génie Logiciel'), ('ENERGIE RENOUVELABLE', 'Energie Renouvelable'), ('INFO-COM', 'Information & Communication'), ('ECONOMIE-GESTION', 'Economie & Ingénierie Financière / Gestion'), ('RESSOURCES MINERALES', 'Ressources Minérales & Aménagement du sous-sol'), ('PACES', 'PACES'), ('ANESTHESIE', 'Anesthésie & Réanimation'), ('TECH-BIO', 'Technologie Biomédicale')], max_length=50)),
                ('niveau', models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3')], default='L1', max_length=5)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/photos/')),
                ('genre', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('mention', models.CharField(choices=[('INFORMATIQUE', 'Informatique & Génie Logiciel'), ('ENERGIE RENOUVELABLE', 'Energie Renouvelable'), ('INFO-COM', 'Information & Communication'), ('ECONOMIE-GESTION', 'Economie & Ingénierie Financière / Gestion'), ('RESSOURCES MINERALES', 'Ressources Minérales & Aménagement du sous-sol'), ('PACES', 'PACES'), ('ANESTHESIE', 'Anesthésie & Réanimation'), ('TECH-BIO', 'Technologie Biomédicale')], max_length=20)),
                ('niveau', models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3')], default='L1', max_length=5)),
                ('annee', models.CharField(max_length=10)),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assDashboard.semestre')),
            ],
            options={
                'unique_together': {('nom', 'mention', 'semestre', 'annee')},
            },
        ),
    ]
