# Generated by Django 6.0.2 on 2026-02-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assDashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestre',
            name='nom',
            field=models.CharField(choices=[('1', 'Semestre 1'), ('2', 'Semestre 2')], max_length=2, unique=True),
        ),
    ]
