# Generated by Django 6.0.2 on 2026-02-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assDashboard', '0002_alter_semestre_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='semestre',
            field=models.CharField(choices=[('1', 'Semestre 1'), ('2', 'Semestre 2')], max_length=2),
        ),
    ]
