# Generated by Django 6.0.1 on 2026-01-31 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_student_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mention',
            field=models.CharField(choices=[('INFORMATIQUE', 'Informatique & Génie Logiciel'), ('ENERGIE RENOUVELABLE', 'Energie Renouvelable'), ('INFO-COM', 'Information & Communication'), ('ECONOMIE-GESTION', 'Economie & Ingénierie Financière / Gestion'), ('RESSOURCES MINERALES', 'Ressources Minérales & Aménagement du sous-sol'), ('PACES', 'PACES'), ('ANESTHESIE', 'Anesthésie & Réanimation'), ('TECH-BIO', 'Technologie Biomédicale')], max_length=50),
        ),
    ]
