# Generated by Django 6.0.1 on 2026-02-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DELEGATE', 'Delegue'), ('ELEVE', 'Élève')], default='ELEVE', max_length=10),
        ),
    ]
