# Generated by Django 6.0.1 on 2026-02-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DELEGATE', 'Delegue'), ('SUPPLEANT', 'Suppleant'), ('ELEVE', 'Élève')], max_length=10),
        ),
    ]
